[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}

l3gion_rust = { git = "https://github.com/Cunha-Renato/l3gion_rust" }

[profile.release]
lto = true
codgen-units = 1
panic = "abort"